//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksManager.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public Nullable<int> price { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public Nullable<int> Id_StivenKing { get; set; }
        public Nullable<int> Id_GowardLavCraft { get; set; }
        public Nullable<int> Id_JorgOryel { get; set; }
    
        public virtual GowardLavCraft GowardLavCraft { get; set; }
        public virtual JorgOryel JorgOryel { get; set; }
        public virtual StivenKing StivenKing { get; set; }
        public virtual StivenKing StivenKing1 { get; set; }
    }
}
